### ISSUE TITLE
Modify or complete the white-paper to clarify the continuity and operation of the protocol in the future.

### ISSUE THREAD

**Issue by 0xsingular** [teaxyz/white-paper#109]
As mentioned in part “[TEA Token Supply Distribution](https://github.com/teaxyz/white-paper/blob/main/white-paper.md#tea-token-supply-distribution)” of the white-paper as "_a 10 billions **MAXIMUM** token supply will be distributed_", and 50% will be allocated towards _Ecosystem & Governance_, and from this allocation a portion will be distributed as staking and Proof of Contribution rewards + other incentives.

Considering that The Tea Protocol will grow and mature and over time the amount of tokens allocated to Ecosystem & Governance will be consumed by staking rewards, proof of contribution rewards, incentives...
The TEA token has a crucial role within the protocol according to the white-paper, so if there will be no staking rewards and Proof of Contribution rewards, **how** will the protocol operate after this stage if we have a **MAXIMUM** amount?

So some information needs to be added or modified, or the TEA will be an inflationary token, or the governance/team will decide the operating model after consuming this allocation, or whatever note needs to be added for more clarity on this aspect.

**Comment by thomas-borrel** [comment]
Hi,
Thanks for your comment. 
- The current plan is to mint all 10b tokens at TGE (token generation event), currently scheduled for Q2 2024.
- The emissions curve for both staking rewards and Proof of Contribution rewards are planned over 50 years. i.e. TEA’s emissions curve is conservative and spans over 50 years with a majority of the token supply introduced programmatically based on network participation.
- TEA is a deflationary token. Some tokens will be burnt using mechanisms described in the white paper.

Mechanisms are built into the protocol to further extend both emission curves by injecting tokens back into these pools, with a plan to add more as part of the roadmap.
Here's one example for staking rewards: As staking rewards trickle from one project to its dependencies, any rewards destined to a dependency that is not registered with the protocol are put back into the staking rewards distribution pool, thus extending the emissions curve.

Our goal is to publish a more comprehensive paper on the tokenomics between now and TGE. I understand the white paper doesn't have all the details, and it wasn't intended to. There was a lot of ground to cover already, and we opted to supplement it with additional papers that will be published over time. One will be on the tokenomics, with another providing more details on proof of contribution.

Thanks again for your comment! Great to see tea enthusiasts wanting to understand the details of the protocol!

**Comment by 0xsingular** [comment]
Thanks for your time and detailed response, I now have more understanding of how this mechanism will work.

I love how the _tea_ team engages in communication with devs and the community!
