### ISSUE TITLE
Georgia doesn't include glyphs for Chinese and Korean

### ISSUE THREAD

**Issue by mfts** [teaxyz/white-paper#90]
Georgia is great for Cyrillic. 

However, it doesn't support Chinese, Korean or Japanese characters.

I think we have two options:

1. We decide to go with one font for all translations like Noto https://en.wikipedia.org/wiki/Noto_fonts 
2. We use specialty fonts for each language group, Georgia for Cyrillic, Noto CJK for Chinese/Korea, etc

**Comment by mxcl** [comment]
Let’s try out noto and see how it looks for English.

**Comment by mfts** [comment]
Closed with #92
